add Scientific
RyanGlScott/text-show-instances pull request #12
Opened 2021-11-20 04:12 UTC by stevemao

2021-11-20 12:49 UTC, RyanGlScott requested changes
Thanks for the PR! To make sure that this is working properly, can you:

* Add the new `TextShow.Data.Scientific` module to `text-show-instances.cabal`, and
* Add a test case in the test suite? That way, we can ensure that the behavior of the `TextShow` instance for `Scientific` matches that of its `Show` instances. [Here](https://github.com/RyanGlScott/text-show-instances/blob/c2bb8cbfa27dd5a4aa33c67f7d5d2b64a0be3448/tests/Spec/Data/ShortTextSpec.hs) is an example test case from which to take inspiration.

2021-11-21 02:43 UTC, stevemao commented
@RyanGlScott fixed. thanks

2021-11-21 14:38 UTC, RyanGlScott approved these changes

2021-11-21 14:38 UTC, merged

2021-11-21 15:10 UTC, RyanGlScott commented
I've uploaded [`text-show-instances-3.8.6`](https://hackage.haskell.org/package/text-show-instances-3.8.6) to Hackage with these changes.